language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_PROJECT=UnboxedAlamofire.xcodeproj
  matrix:
    - SCHEME="UnboxedAlamofire-iOS"
    - SCHEME="UnboxedAlamofire-OSX"
    - SCHEME="UnboxedAlamofire-tvOS"

before_install:
  - carthage bootstrap  
  
script:
  - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
