language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=UnboxedAlamofire.xcworkspace

before_install:
  - carthage bootstrap  
  
script:
  - xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme UnboxedAlamofire-iOS -destination "platform=iOS Simulator,name=iPhone 6" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
